services:
  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=DevPassword162!
      - MSSQL_PID=Developer

      - "1433:1433"
    volumes:
      - ./sqlserver-data:/var/opt/mssql/data

  app-spring:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db-sqlserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db-sqlserver:1433;databaseName=employees;encrypt=true;trustServerCertificate=true;createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=DevPassword162!
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.SQLServerDialect

volumes:
  sqlserver-data: